### ISSUE TITLE
Change the name?

### ISSUE THREAD

**Issue by mallowigi** [a8m/angular-filter#10]
Angular filter is a too common name, easily mistaken with angular filters feature.

I suggest a cooler name, something of the sort of Bower, Mimosa, Boba or Grunt.

It needs to be something related to filters. What about "ngPipes"? Since filters are using pipes ( | ) this could be a cool name no?

**Comment by ccortezia** [comment]
+1

**Comment by AJeezy9** [comment]
Yet another +1

**Comment by stereokai** [comment]
Ha. Guess this ain't happening any time soon ;)
