### ISSUE TITLE
Add option .join by property

### ISSUE THREAD

**Issue by qwert789** [a8m/angular-filter#111]
In join filter add option to specify property to join array of objects, for example:
<code>
var users = [
      {name: "Joe", age: 22},
      {name: "Kevin", age: 24},
      {name: "Peter", age: 21}
    ];
</code>
  {{ users | join:'name' }}

will result:
Joe,Kevin,Peter

**Comment by a8m** [comment]
What about ` {{ users | map: 'name' | join }} ` ?

**Comment by qwert789** [comment]
@a8m thnx this is great, never thought that i can combine map and join together, probably it worst to add such example to the docs.
