### ISSUE TITLE
filter matching 2 array 

### ISSUE THREAD

**Issue by wesley3523** [a8m/angular-filter#116]
i have a couple of checkboxes (modelTest are the values) that i want to match with the branchetest.

    $scope.modelTest = [1, 2];
    $scope.branchetest = [
        { id: 1, branches: [{brancheId: 1}, {brancheId: 2}]}, 
        { id: 2, branches: [{brancheId: 3}, {brancheId: 2}]}
        { id: 3, branches: [{brancheId: 3}, {brancheId: 4}]} 
    ];
I already tried (branchetest | map: 'branches' | flatten | where: {brancheId: [1, 2]}) but doesnt give me any result. In this example i would like to see only the first and second object because of the branche id's matching. Can you help me with a solution?

**Comment by a8m** [comment]
Hi @wesley3523 
PTAL on this example: [jsbin](http://jsbin.com/tovicu/1/edit?html,js,output) and please let me know if this help you (I hope I got your intentions right).

Thanks.

**Comment by wesley3523** [comment]
Thanks for the reply and example. What i want in the below example is to output only the first 2 objects so { id: 1 ...} and { id: 2 ...} in my ng-repeat output.

$scope.branches = [
      { id: 1, name: 'should show this item', branches: [{brancheId: 1}, {brancheId: 2}]}, 
      { id: 2, name: 'should show this item', branches: [{brancheId: 3}, {brancheId: 2}]},
      { id: 3, name: 'should not show this', branches: [{brancheId: 3}, {brancheId: 4}]} 
    ];
    $scope.ids = [1, 2, 7, 10];
    // ngRepeat callback
    $scope.hasId = function(el) {
      return ~$scope.ids.indexOf(el.id);    
    };

I hope you can help me with that, Thank you i appreciate it.

**Comment by a8m** [comment]
Sorry, but I didn't understand your example.
Can you please try to provide a new one with different fields, and the output that you want.(try to not repeat on the same `id` twice).
Thanks.

**Comment by wesley3523** [comment]
i already made a custom filter. Check this fiddle for example http://jsfiddle.net/6mqbm/

**Comment by a8m** [comment]
Great.
based on your example: [jsbin](http://jsbin.com/tupajo/1/edit?html,js,output)
