### ISSUE TITLE
groupBy coerces numeric key into a string

### ISSUE THREAD

**Issue by toolbear** [a8m/angular-filter#123]
The `groupBy` filter coerces a numeric key into a string for the iterator variable. This breaks code that expects to do `===` checks on the ID, such as operating on all items within a group.

Given data like:

```javascript
$scope.personel = [
  { name: 'Kirk', unitID: 1, unit: 'Command' },
  { name: 'Scotty', unitID: 2, unit: 'Engineering' },
  { name: 'Spock', unitID: 2, unit: 'Engineering' }
]
```

and a template like:

```html
<ul>
  <li ng-repeat="(unitID, rows) in personel |groupBy: 'unitID'">
    Unit: {{ rows[0].unit }}
    <button ng-click="selectAllInUnit(unitID)"></button>
    <ul>
      <li ng-repeat="person in rows">…</li>
    </ul>
  </li>
</ul>
```

And `selectAllInUnit()` similar to:

```javascript
function selectAllInUnit(unitID) {
  _.chain(personel)
    .filter(function(person) { return person.unitID === unitID); })
    .each(…);
}
```

The filter predicate will fail because `person.unitID` is a number and `unitID` arg was coerced to a string by `groupBy`.

**Comment by toolbear** [comment]
My workaround was to do this in the template:

```html
<button ng-click="selectAllInUnit(rows[0].unitID)"></button>
```

**Comment by a8m** [comment]
I think this issue belongs to `ngRepeat` directive.
see: [example](http://jsbin.com/webefe/2/edit?html,js,output)

Thanks @toolbear

**Comment by toolbear** [comment]
For posterity, I eventually settled on this workaround using `ng-init`:

```html
<ul>
  <li ng-repeat="(unitIDString, rows) in personel |groupBy: 'unitID'" ng-init="unitID = rows[0].unitID">
    Unit: {{ rows[0].unit }}
    <button ng-click="selectAllInUnit(unitID)"></button>
    <ul>
      <li ng-repeat="person in rows">…</li>
    </ul>
  </li>
</ul>
```
