### ISSUE TITLE
Limit by index count based on filter

### ISSUE THREAD

**Issue by RemeJuan** [a8m/angular-filter#126]
Hey,

I am just wondering if there is a way to limit based on what was filters, I have an array of 25 items coming back. 5 items belong to 1 side of the page and the other 20 on the other.

Previously I had these as 2 nested objects and was able to use g-show="$index>otherskill.length/2-1"
This pluggin is the perfect solution for an idea/problem I had with moving my data into mongo and getting a clean and unified way of getting varying collections with different schemas back.

I cannot seem to find anything in the readme that hints to how to do this, already tried running it to an array and applying said array name to the above show function and that did not work.

Thanks

**Comment by a8m** [comment]
Can you please provide some jsbin/fiddle example that demonstrate this ?
Thanks @RemeJuan .

**Comment by RemeJuan** [comment]
Hey @am8, as requested, here is pretty much exactly what I am trying to achieve.
As you can see there were 2 scopes in that scenario, so it was easy to pull off the index length check.

Thanks
