### ISSUE TITLE
How about a "get" filter?

### ISSUE THREAD

**Issue by Harper04** [a8m/angular-filter#129]
Not sure if there is a better standard way but this is what i am missing:
```
priorities = [{name:"bla", role:1},{name:"blo",role:2},{name:"bli",role:3}]
{{priorities | filterBy: ['role']:clientSession.role | first | get:'name'}}
```
without ```get``` i get an object and no way to display only the name

i wrote this:
```
(function() {
  "use strict";
  module.exports = function() {
    return function(input,param) {
        return input[param];
    };
  };

}).call(this);
```

**Comment by a8m** [comment]
You can simply do it like this: 
```
{{ (priorities | ... | first).name }}
```
PTAL on this [example](http://jsbin.com/cuvuza/edit?html,js,output)
Thanks @Harper04
