### ISSUE TITLE
GroupBy + OrderBy not working

### ISSUE THREAD

**Issue by dangnelson** [a8m/angular-filter#136]
I want to groupBy a different value then I want to orderBy. Can't get it to work. Looked at other issues in the forum, but they all seemed to be for using the SAME value, not different values.

    	<div ng-repeat="(key, value) in wishes | groupBy: 'ownedUser.id' | orderBy: 'ownedUser.lastName' " >
			<div ng-repeat="wish in value" ng-show="$first">
				{{ wish.ownedUser.firstName }} {{ wish.ownedUser.lastName }}
			</div>
			
			<div ng-repeat="wish in value  | orderBy: 'wish.dateCreated'" >
				<h2>{{ wish.name }}</h2>
			</div>
    	</div>

**Comment by a8m** [comment]
Hi @dangnelson,
You should use [toArray](https://github.com/a8m/angular-filter#toarray) filter before the orderBy filter to control the order of the groups(see my comment [here](https://github.com/a8m/angular-filter/issues/57#issuecomment-65041792))

It will be great if you provide me some snippet of your data, so I can create a *jsbin*-example for you.
Thanks.

**Comment by dangnelson** [comment]
Still couldn't get it to work with this modification:

    <div ng-repeat="(key, value) in wishes | groupBy: 'ownedUser.id' | toArray:true | orderBy: 'ownedUser.lastName' " >
        <div ng-repeat="wish in value" ng-show="$first">
            {{ wish.ownedUser.firstName }} {{ wish.ownedUser.lastName }}
        </div>

        <div ng-repeat="wish in value  | orderBy: 'wish.dateCreated'" >
            <h2>{{ wish.name }}</h2>
        </div>
    </div>

Here's some sample data. 

   [{
    "id": 49,
    "dateCreated": 1437672290921,
    "lastUpdated": 1438095789933,
    "name": "Waterfall",
    "imageUri": null,
    "location": "Niagra Falls",
    "price": 1000.0,
    "quantity": 3,
    "comment": "This is a waterfall.",
    "ownedUser": {
        "id": 12,
        "firstName": "Dan",
        "lastName": "Dingle"
    },
    "claimedUser": null,
    "productLink": null,
    "removed": false
    }, {
    "id": 61,
    "dateCreated": 1438191480098,
    "lastUpdated": 1438196925079,
    "name": "Cup",
    "imageUri": null,
    "location": null,
    "price": 0.0,
    "quantity": 0,
    "comment": null,
    "ownedUser": {
        "id": 79,
        "firstName": "Billy",
        "lastName": "Bob"
    },
    "claimedUser": {
        "id": 1,
        "firstName": "Brian",
        "lastName": "Brown"
    },
    "productLink": null,
    "removed": false
    }, {
    "id": 50,
    "dateCreated": 1437672443263,
    "lastUpdated": 1438179755154,
    "name": "Waterfall 2",
    "imageUri": null,
    "location": null,
    "price": 0.0,
    "quantity": 0,
    "comment": null,
    "ownedUser": {
        "id": 12,
        "firstName": "Adam",
        "lastName": "Angle"
    },
    "claimedUser": {
        "id": 1,
        "firstName": "Brian",
        "lastName": "Brown"
    },
    "productLink": null,
    "removed": false
    }, {
    "id": 60,
    "dateCreated": 1438191134512,
    "lastUpdated": 1438191191341,
    "name": "Sunglasses",
    "imageUri": null,
    "location": null,
    "price": 0.0,
    "quantity": 0,
    "comment": null,
    "ownedUser": {
        "id": 79,
        "firstName": "Carrie",
        "lastName": "Clapper"
    },
    "claimedUser": null,
    "productLink": null,
    "removed": false
    }]

**Comment by a8m** [comment]
Thanks @dangnelson 
I created some [example](http://jsbin.com/qifejo/edit?html,output) based on your data(hope I get you right).
