### ISSUE TITLE
How can I use groupBy with countBy?

### ISSUE THREAD

**Issue by moneytree-doug** [a8m/angular-filter#137]
I want to group the results with a count for each group. Is it possible to chain these methods?

**Comment by a8m** [comment]
Can you give me some input/output example @moneytree-doug ?, it will be very helpful.

**Comment by moneytree-doug** [comment]
I figured it out. I just used groupBy and checked the length of the array for each group.

**Comment by a8m** [comment]
Great,
Thanks.
