### ISSUE TITLE
impossible to install npm dependencies on a fresh system

### ISSUE THREAD

**Issue by Jandalf** [a8m/angular-filter#139]
if you check out this repository and do a "npm install" you get errors like on this travis build of my pull request:

https://travis-ci.org/a8m/angular-filter/builds/71666732

PR #133

**Comment by a8m** [comment]
Thanks for reporting this issue @Jandalf .
Fixed via ed3b985
see: [build-490](https://travis-ci.org/a8m/angular-filter/builds/74576092)
