### ISSUE TITLE
chunkBy causes infinite digest loop

### ISSUE THREAD

**Issue by sbuhr** [a8m/angular-filter#145]
I wrapped it up in a plunkr.

http://plnkr.co/edit/3JGhbniXJbqEG5TEcEqY?p=preview

Any help appreciated

**Comment by a8m** [comment]
Thanks for point it out @sbuhr, I'll try to fixed it asap.

**Comment by sbuhr** [comment]
See PR #146

**Comment by sbuhr** [comment]
Hm, the test fails. But it works as expected. Probably a digest/memoized issue. I'm fairly new to angular and javascript. I'll try to fix the test as well.

**Comment by Silentspy** [comment]
Is this PR getting merged? having the same issue

**Comment by vip9** [comment]
#147  fixes chunkBy 10 $digest() for me too.

**Comment by nobillygreen** [comment]
Did this ever get fixed? I can verify that it was still an issue for me today. I'm on v0.5.5, and I pulled it from npm today.

**Comment by sbuhr** [comment]
I don't know why it hasn't been merged yet. Tests pass and everything is working. 

@a8m , please review the PR #147

Thanks!

Von meinem iPhone gesendet

**Comment by a8m** [comment]
Sorry about the delay guys, I was a bit busy these last days.

Thanks for the PR @sbuhr, I'm gonna merge it, add some things and release a patch.

**Comment by a8m** [comment]
Hey guys, please check out this [example](http://jsbin.com/lidupu/edit?html,js,output) that based on __v0.5.6__ version, and let me know if there's any problems.

Thanks.

**Comment by Delagen** [comment]
npm contains only 0.5.5

**Comment by a8m** [comment]
Sorry, I forgot to publish. [check it now](https://www.npmjs.com/package/angular-filter) :shipit: 

Thanks.

**Comment by cyrilepinat** [comment]
Hi 
I think this issue is not fixed, I'm on 0.5.8 and I'm still facing chunkBy infinite digest loop problem. 
Any help ?
Thanks

**Comment by danicomas** [comment]
@cyrilepinat I have the same problem too

**Comment by zombiehugs** [comment]
0.5.15 appears to still have chunkBy digest issue. Is there a known fix or way around?
