### ISSUE TITLE
Add fuzzy/fuzzyBy support to accented characters

### ISSUE THREAD

**Issue by micaeldias** [a8m/angular-filter#151]
For example, when the search is "A", the filter would find any of these : "AÂÃÄÀÁÅÆ".

I think this is a complete list of accentes charachters:
ÂÃÄÀÁÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞß
àáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ

Thank you for your work so far.

**Comment by micaelpdias** [comment]
After some research I think this is it: 
{
  "A": "ÁáÀàÄäÂâÃãÅå",
  "D": "Đð",
  "E": "ÉéÈèËëÊê",
  "I": "ÍíÌìÏïÎî",
  "O": "ÓóÒòÖöÔô",
  "U": "ÚúÙùÜüÛû",
  "Y": "ÝýŸÿ",
  "N": "Ññ",
  "C": "Çç",
  "S": "Šš",
  "Z": "Žž"
}

**Comment by micaelpdias** [comment]
Actually found something much more complex http://stackoverflow.com/questions/227950/programatic-accent-reduction-in-javascript-aka-text-normalization-or-unaccentin
