### ISSUE TITLE
Max does not work as documented

### ISSUE THREAD

**Issue by Hacktivista** [a8m/angular-filter#159]
I've been struggling because max or min filter was not working for me, but later I've tried as documented, and didn't work neither, so I guess something is not good.

Here is the documentation: https://github.com/a8m/angular-filter#max
Here is the documentation-based Plnkr: http://plnkr.co/edit/Cqdmt7k1oGYrhPsZpxKo?p=preview

As you can see, the simpler example works, but not the other one

**Comment by a8m** [comment]
It works fine. see [example](http://jsbin.com/terofec/edit?html,js,output)
please note that the `$scope` should be inside a controllerX that bind to some view.

Thanks.
