### ISSUE TITLE
filterBy doesn't have a strict mode

### ISSUE THREAD

**Issue by serpicolugnut** [a8m/angular-filter#163]
When using filterBy, I've noticed that it doesn't have a strict mode.

For example:

Say I have a select list that I'm using to filter my data by. And I have 2 items in there:

Hodgkin Lymphoma
Non-Hodgkin Lymphoma

If I select 'Hodgkin Lymphoma', I get hits containing 'Non-Hodgkin Lymphoma', because it contains 'Hodgkin Lymphoma' in the string match. There should be a mode or modifier that will require the match to be strict, and only match the strings when they are exact matches.

**Comment by a8m** [comment]
Hi @serpicolugnut 
Can you please provide some fiddle/jsbin example ? thx

**Comment by serpicolugnut** [comment]
Sure. See Plnkr here: http://plnkr.co/edit/c2NPkf?p=preview

On the select list titled "Select Number"... you'll see 2 options (among the others)

TIMBUKTU
TIMBUKTU-2

if you select TIMBUKTU, you will get results containing both TIMBUKTU and TIMBUKTU-2, since 'TIMBUKTU-2' contains the string 'TIMBUKTU'. 

The built in Angular Filter contains an option to make the check strict, so only an exact match returns. It would be nice if angular-filter had a similar option.

**Comment by toddbranch** [comment]
@a8m I'm happy to work the PR for this, if this is something you think should be included.

**Comment by a8m** [comment]
Yes, we should add a strict mode support.
Thanks @toddbranch, feel free to PR.

**Comment by sesubash** [comment]
bower version doesn't have this update. Please fix it.

**Comment by judezhu** [comment]
+1. bower version is not updated.
