### ISSUE TITLE
"max" and "min" filters work incorrectly with Date objects

### ISSUE THREAD

**Issue by tsareg** [a8m/angular-filter#168]
E.g. in controller
```javascript
$scope.arr = [ { date: new Date() }, { date: new Date() } ];
```
and then in template
```html
{{ arr | max:'date' }}
``` 
will output nothing.
This happens due to conversion of Date objects to milliseconds by  Math.max/Math.min in https://github.com/a8m/angular-filter/blob/master/src/_filter/math/max.js#L32 while *mappedArray* contains Date objects.

Now workaround is to pluck date field and then apply max. In that case we will have number of milliseconds in output:
```html
{{ arr | map:'date' | max }}
```

**Comment by toddbranch** [comment]
@a8m this looks legit - do you want PRs?

**Comment by a8m** [comment]
what do you think about these examples @tsareg ?
- `{{ arr | max: 'date.getTime()' }}`


- `{{ arr | max: comp }}`
  ```js
  $scope.comp = function (el) {
    return el.date.getTime();
  };
  ```

PTAL on this [jsbin-example](http://jsbin.com/jiguja/edit?html,js,output), thx.

**Comment by tsareg** [comment]
@a8m Yep, I've already used it as workaround.
