### ISSUE TITLE
GroupBy vs CountBy

### ISSUE THREAD

**Issue by claudiolassala** [a8m/angular-filter#172]
Hi, there!

Is it possible to GroupBy a criteria (so I can have access to things I'm groupping by) but still get a CountBy for each item in the group?

Thanks in Advance,

Claudio

**Comment by jeserkin** [comment]
Wouldn't it be the same as `(key, value) in collection | groupBy: 'property'` and inside `value.length`. Or you wan't to have the ability to count without grouping?

**Comment by claudiolassala** [comment]
(double face palm) Dude... value.length... duh... that does it. Thanks!!
