### ISSUE TITLE
add sum on array

### ISSUE THREAD

**Issue by moshfeu** [a8m/angular-filter#191]
This should looks like:

**controller**
`$scope.users = [
  { user: { score: 988790 } },
  { user: { score: 123414 } },
  { user: { score: 987621 } }
];`

**view**
`<p> {{ users | sum: 'user.score' }}</p>`

**result**

`<p>2099825</p>`

Similar to [`min`](https://github.com/a8m/angular-filter#min) filter

Thanks

**Comment by toddbranch** [comment]
I think this might work:
`{{users | map: 'user.score' | sum}}`

**Comment by moshfeu** [comment]
Thanks! Works like charm ;)

**Comment by moshfeu** [comment]
I have another question.. My data is array of arrays like this:

`$scope.data = [[1460232000000,2],[1460235600000,5],[1460239200000,7]];`

My final goal is to sum the second number of each array, for this data `14`.

I know that I need to do `sum` on `map` but I can figure how.

I started with the `map` on `ng-repeat` but it's show the full array. 

`<div data-ng-repeat="aa in data track by $index | map: 'aa[0]' ">{{aa}}</div>`

Here is my poor result in a bin:

http://jsbin.com/laheho/edit?html,js

Thanks!

**Comment by toddbranch** [comment]
Hi @moshfeu.  Here's a solution:
```
// in controller
$scope.secondElement = function(item) {
  return item[1];
};

// in HTML
<div data-ng-repeat="aa in data | map: secondElement track by $index ">{{aa}}</div>
```

If there's a way to make an angular expression that access the second element of the array, this would be a bit simpler.  But I can't figure out if that's possible.

**Comment by moshfeu** [comment]
Thanks! I got this from the docs but I hoped that this is can be done by expression. Pretty annoying. Thank you any way. I really appreciate it!
