### ISSUE TITLE
Ordering numbers in groupBy

### ISSUE THREAD

**Issue by pichotweb** [a8m/angular-filter#193]
Hello,

I have the following collection to group and order:

[
  {
    "name":"John",
    "group_id": "1"
  },
  {
    "name":"Doe",
    "group_id": "2"
  },
  {
    "name":"Lorem",
    "group_id": "10"
  }
]

When I group and order the array by group_id, the final final order is:

[1,10,2]

Does have any options to change this behavior?

Thanks!

**Comment by toddbranch** [comment]
Yeah, your numbers are being sorted as strings - so that's the proper sorted order. Make sure they're numbers and it should work.

**Comment by pichotweb** [comment]
@toddbranch  thanks for the reply!

Even returning an Int the behavior is the same.

**Comment by toddbranch** [comment]
You can pass a custom comparator function to orderBy - that should do it.

**Comment by pichotweb** [comment]
It's solved now! the problem was that the collection had object instead of array, the filter expects to order properly, I've added a filter "toArray", and I called the orderBy after it. Thanks for the help!

**Comment by onigetoc** [comment]
@pichotweb any example? 
do not work for me

**Comment by pichotweb** [comment]
I didn't find the example to show for you. I don't remeber which project I used this solution, but as I said above my problem was that my controller as return a JS Object, so the order was with an unenxpected behavior, when I tranformed it on an Array, the sort was done correctly, I'll continue search the code, as long I find it I'll paste here for you. Hope it help!
