### ISSUE TITLE
Support CommonJS 

### ISSUE THREAD

**Issue by sibelius** [a8m/angular-filter#212]
For better compatibility with webpack and browserify
Ref: http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

check this - https://github.com/lorenzofox3/Smart-Table/issues/428

**Comment by a8m** [comment]
Hi @sibelius, would you like to create a PR for this? thanks

**Comment by a8m** [comment]
Closed via #213

**Comment by sibelius** [comment]
tks

**Comment by sibelius** [comment]
could u please release a new version on npm?

**Comment by a8m** [comment]
done

**Comment by sibelius** [comment]
tks
