### ISSUE TITLE
Where filter - Error: object is null

### ISSUE THREAD

**Issue by danielbair** [a8m/angular-filter#225]
Trying to do...
var cycles = $filter('where')(obj,{cycle_start: 'true'});

But getting...
Error: object is null

**Comment by a8m** [comment]
Hey @danielbair 
Sorry for the late response.
I don't see any issue with that. here's a [jsbin](https://jsbin.com/gaxikap/edit?html,js,output) follows your example.
Feel free to open the issue if you still have any trouble with angular-filter.
