### ISSUE TITLE
Angular version 1.4.3

### ISSUE THREAD

**Issue by pmcalmeida** [a8m/angular-filter#234]
Is there any specific reason to require angular 1.4.3? Can you make it for angular >= 1.4.3?
We are using it with angular 1.5.7 with no issue.

**Comment by roger2hk** [comment]
A PR #233 has been created. However, the `travis-ci` failed due to an unknown issue.

**Comment by evilaliv3** [comment]
yep it would be imporant to solve this to not make people think that the library works only on 1.4.3 and abandon its usage.

also on [GlobaLeaks](github.com/globaleaks/GlobaLeaks) we are waiting for this fix in order to update to 0.5.12.

thanks!

**Comment by a8m** [comment]
Solved with #233. new version published.
Thanks guys
