### ISSUE TITLE
Getting false back on 'Every' Filter 

### ISSUE THREAD

**Issue by westerncj** [a8m/angular-filter#243]
I can't seem to get the `every` filter to work. I keep getting false back.

Here is an example. I have a collection like this:
```
var myCollection = [{ Id: 1, selected: true }, { Id: 2, selected: true }]
{{ myCollection | every: selected == true }}
```

I've also tried `{{ (myCollection | every: {selected: true}) }}`, but I still get false.

**Comment by a8m** [comment]
Hey @westerncj 
The expression should be type string. I fixed the example in the README, see [every example](https://github.com/a8m/angular-filter/#every).

I'm gonna close this issue, but feel free to open it if you still have issue with that.
