### ISSUE TITLE
Unknown provider error for phoneUS

### ISSUE THREAD

**Issue by njcoutinho** [a8m/angular-filter#248]
I have included the module in my app, However I only get the unknown provider error when using the 
phoneUS filter, other filters like ucfirst work fine

Unknown provider: phoneUSFilterProvider <- phoneUSFilter

Using @version v0.5.15 - 2017-01-17

**Comment by a8m** [comment]
Hey @njcoutinho, thanks for letting me know that.
I released a new version v0.5.16.

I'm closing this issue, but don't hesitate to open it  if you still have problem.

**Comment by njcoutinho** [comment]
v0.5.16 works. Thank you
