### ISSUE TITLE
BroupBy hide parent when filtering

### ISSUE THREAD

**Issue by ahmedmrj** [a8m/angular-filter#257]
Hello, I am using groupBy filter for creating nested tree from object, and I want to hide parent on filtering with an input. if it doesn't have any matching child.

My html code look like this:

```
<div>
<input type="text"  ng-model="mySearchFilter">
<ul>
  <li ng-repeat="(key, value) in players | groupBy: 'team'">
    Group name: {{ key }}
    <ul>
      <li ng-repeat="player in value | filter: mySearchfilter">
        player: {{ player.name }}
      </li>
    </ul>
  </li>
</ul>
</div>
```

**Comment by fikoborquez** [comment]
You can use **filterBy** before groupBy team in the first repeat instead of filtering in the second repeat.
I made an [example](https://plnkr.co/edit/0dSbHqd7Go7HkZQi31CF).

**Comment by ahmedmrj** [comment]
yess!!! many thanks f**ikoborquez**.
