### ISSUE TITLE
orderBy not working with groupBy

### ISSUE THREAD

**Issue by arturokunder** [a8m/angular-filter#26]
When you make a groupBy, filterBy is not working

For example:

```
[
  {
    category: 'alpha',
    id: 3,
    group: 'a'
  },{
    category: 'beta',
    id: 2,
    group: 'a'
  }, {
    category: 'gamma',
    id: 1,
    group: 'b'
  }
]
```

if you make 

```
ng-repeat="(i, category) in array | orderBy: 'id' | groupBy: 'group' "
    {{ i }}
    ng-repeta="item in category" 
    {{ item.category }}
```

It's render:
    a
    alpha
    beta
    b
    gamma

instead of
   b
   gamma
   a
   beta
   alpha

**Comment by Emerson-Coelho** [comment]
`
        <ul>
          <li ng-repeat="gp_up in necessidade.estacoes | groupBy:'GP_ID' | orderBy: 'GP_DESCRICAO'">
            GP: {{ gp_up[0].GP_ID }}  - {{ gp_up[0].GP_DESCRICAO }}
            <ul>
              <li ng-repeat="up_estacao in gp_up | groupBy: 'UP_ID' | orderBy: 'UP_DESCRICAO'">
                UP: {{ up_estacao[0].UP_ID }} - {{ up_estacao[0].UP_DESCRICAO }}
                <ul>
                  <li ng-repeat="estacao in up_estacao | orderBy: 'ESTACAO_DESCRICAO'">
                    ESTACAO: {{ estacao.ESTACAO }} - {{ estacao.ESTACAO_DESCRICAO }}
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
`
How to this case?
If you enter a new grouping, how do I re-order?
