### ISSUE TITLE
[Suggestion] change current ucfirst behvaior with ucwords, and change ucfirst to uppercase the first word.

### ISSUE THREAD

**Issue by danrevah** [a8m/angular-filter#48]
The current behavior of ucfirst is acting werid.
its uppercasing all of the words in the sentence.
I think it should behave like in PHP, that its uppercasing only the first word.
if you want to uppercase all of the words you can create a ucwords filter.
anyway I've forked the project and made the changes.
ucfirst - will uppercase only the first letter in the first word
ucwords - will behave like ucfirst used to. it will uppercase the first letter in all of the words.
also i've added
lcfirst, lcwords, and nl2br which was needed in my project.

PHP Resources:
http://php.net/manual/en/function.ucfirst.php
http://php.net/manual/en/function.ucwords.php

**Comment by DiederikvandenB** [comment]
I wonder, why is this closed. I rather agree with @danrevah

**Comment by andreaslarssen** [comment]
+1
