### ISSUE TITLE
0.5.0 digest cycle error with group by.

### ISSUE THREAD

**Issue by niemyjski** [a8m/angular-filter#52]
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: function () {\n                var start = performance.now();\n                var ret = w.apply(this, arguments);\n                var end = performance.now();\n                debug.watchPerf[watchStr].time += (end - start);\n                debug.watchPerf[watchStr].calls += 1;\n                return ret;\n              }; newVal: 983; oldVal: 981"],["fn: function () {\n                var start = performance.now();\n                var ret = w.apply(this, arguments);\n                var end = performance.now();\n                debug.watchPerf[watchStr].time += (end - start);\n                debug.watchPerf[watchStr].calls += 1;\n                return ret;\n              }; newVal: 985; oldVal: 983"],["fn: function () {\n                var start = performance.now();\n                var ret = w.apply(this, arguments);\n                var end = performance.now();\n                debug.watchPerf[watchStr].time += (end - start);\n                debug.watchPerf[watchStr].calls += 1;\n                return ret;\n              }; newVal: 987; oldVal: 985"],["fn: function () {\n                var start = performance.now();\n                var ret = w.apply(this, arguments);\n                var end = performance.now();\n                debug.watchPerf[watchStr].time += (end - start);\n                debug.watchPerf[watchStr].calls += 1;\n                return ret;\n              }; newVal: 989; oldVal: 987"],["fn: function () {\n                var start = performance.now();\n                var ret = w.apply(this, arguments);\n                var end = performance.now();\n                debug.watchPerf[watchStr].time += (end - start);\n                debug.watchPerf[watchStr].calls += 1;\n                return ret;\n              }; newVal: 991; oldVal: 989"]]

projects is set to: [ { "id": "537650f3b77efe23a47914f4", "organization_id": "537650f3b77efe23a47914f3", "organization_name": "Acme", "name": "Disintegrating Pistol", "data": {}, "promoted_tabs": [], "custom_content": null, "stack_count": 0, "event_count": 0, "total_event_count": 306, "last_event_date": "2014-11-11T13:56:48.275Z" }, { "id": "54416dbba397230ba82dd311", "organization_id": "54416dbba397230ba82dd30d", "organization_name": "Test", "name": "Test Project", "data": {}, "promoted_tabs": [], "custom_content": null, "stack_count": 0, "event_count": 0, "total_event_count": 0, "last_event_date": "0001-01-01T00:00:00" } ]

<div ng-repeat="(organization_id, projects) in vm.projects | groupBy: 'organization_id'"></div>

I'm also using the latest stable version of angular 1.3.

**Comment by jomarquez** [comment]
I am using angular-filter 0.5.9 on angular 1.3 and am still getting the  [$rootScope:infdig] error
 on safari only. any one else experiencing this?

**Comment by fredtma** [comment]
Using angular-0.5.16 and angular 1.2.8 and still getting this error

**Comment by fredtma** [comment]
Note: There is an issue (conflict) if you are angular-filter and ng-group, they both use the same filter name 'groupBy'
