### ISSUE TITLE
GroupBy + OrderBy not working

### ISSUE THREAD

**Issue by jtomek** [a8m/angular-filter#57]
Hi guys,

I can't get OrderBy to work with GroupBy. 

ng-repeat="(key, value) in memories | groupBy: 'groupDate' | orderBy : '-groupDate'

orderBy does not work.

groupDate is a normal date (2014/11/29)
I also tried using value.data.groupDate[0]; Not working too.

Nothing seems to change the order.

Could you please advice?

Thanks and best regards,
Jakub

**Comment by theraku** [comment]
Hello guys,
@a8m Can you tell me why groupBy with toArray doesn`t work ? 
http://plnkr.co/edit/G6sHrEHQIGVBwzolxlYb?p=preview

**Comment by evilaliv3** [comment]
@a8m : i've implemented the solution that you suggest in https://github.com/a8m/angular-filter/issues/57#issuecomment-65041792 but it appears to me to trigher a 100% cpu as probably the digest loop never finish. is there any alternative?

**Comment by evilaliv3** [comment]
ok it was my fault as im using it with nested forms inputs so that i've to benefit of the onetime binding (::) in order to evaluate it only once.

**Comment by rkingon** [comment]
I found the performance on the `| toArray: true | orderBy: customMappingFunction` method to be terrible. I came up with a solution that keeps performance up and produces the correct result -- (although it does seem a bit odd!)

	<div ng-repeat="(key, results) in allResults | groupBy: '-someKey' )">
		<h3>{{ key | ltrim: '-' }}</h3>
		<ul>
			<li ng-repeat="result in results">
				{{ result }}
			</li>
		</ul>
	</div>
For whatever reason, adding the `-` does force the `groupBy` to sort correctly, but it also adds it to the `key`, so we can just remove it!

**Comment by chenyilei** [comment]
> Thank you very much for your reply!
> 
> I have already seen this entry. I think it does not fit to my problem.
> 
> All of my entries have a created_at date. I group these entries by month and year. I have for example the following groups:
> 
> ##### Raw Input (random)
> * November 14,
> * October 13
> * December 14,
> * November 13,
> 
> I would like to get (newest groups first)
> 
> ##### Expected Output
> * December 14
> * November 14
> * November 13
> * October 13
> 
> I understand that I can format the date in one way (2014/12, 2014/11, 2013/11, 2013/10) for the grouping and I can then format the view in a more readable way (December 14), that is no problem. So right now, the grouping is ordered like this:
> 
> ##### Current Output
> * 2013/10
> * 2013/11
> * 2014/11
> * 2014/12
> 
> I would like to order the groups by -groupDate (reverse).
> 
> In future, I may want to add additional possibilities of grouping, such as numbers, Group names.
> 
> How to achieve this functionality?
> 
> I look Forward your reply,
> Jakub

good

**Comment by chenyilei** [comment]
> Hi @jtomek , see issue #26
> **quote:** `orderBy` must be the last filter in the chaining (when you apply filter to the result of another filter).
> But, `groupBy` return an object, and `orderBy` expect array as an arguments.
> So, you can do something like that:
> 
> ```js
> $scope.groups = [
>     { category: 'alpha', id: 2 },
>     { category: 'beta',  id: 3 }, 
>     { category: 'gamma', id: 0 },
>     { category: 'alpha', id: 4 },
>     { category: 'beta',  id: 5 }, 
>     { category: 'gamma', id: 1 }
>    ];
>   // retrieves the min 'id' of a collection, used for the group ordering.
>   // you can use lodash instead. e.g: _.min(arr, 'id') 
>   $scope.min = function(arr) {
>     return $filter('min')
>       ($filter('map')(arr, 'id'));
>   }
> ```
> 
> ```
>  <ul ng-repeat="group in groups | groupBy:'category' | toArray:true | orderBy:min">
>     
>     <li>{{ group.$key }}</li>
>     
>     <li ng-repeat="item in group | orderBy:'id'">
>       {{ item }}
>     </li>
> </ul>
> ```
> 
> **RESULT:**
> 
> ```
> - gamma
>   - {"category":"gamma","id":0}
>   - {"category":"gamma","id":1}
> - alpha
>   - {"category":"alpha","id":2}
>   - {"category":"alpha","id":4}
> - beta
>   - {"category":"beta","id":3}
>   - {"category":"beta","id":5}
> ```

good for me
