### ISSUE TITLE
[New Feature] .test(), .match() filters

### ISSUE THREAD

**Issue by tak215** [a8m/angular-filter#68]
Hi,

I was thinking of adding passwordFmt which checks whether a string contains 8+ characters, at least one uppercase, lowercase, and a number. There may be a 'strict' option where it also checks for at least one special character.

Let me know what you guys think of this.

Taku

**Comment by mallowigi** [comment]
Not sure it can be qualified as a common case. Password specifications vary from service to service, some being laxer than others (I personally find it bullshit, better passwords are longer passwords, even if it contains only letters, period). What could be useful however, is a pattern matching filter. Something like

```html
<div ng-if="myVar | matches:'/[\w]+/i'">...</div>
```

But even that is not so common.

**Comment by a8m** [comment]
I Agree with @mallowigi, 
pattern matching/testing could be useful, what you do with it, it's your choice.
```js
{{ 'foobarbaz' | test: '/^[a-zA-Z]{3,}$/' }}  // → true
{{ 'foobarbaz' | match: '/[a-zA-Z]{3,}/g' }}  // → ['foo', 'bar', 'baz']
```

**Comment by a8m** [comment]
based on your example @tak215 , I generally use `ng-pattern` to deal with input validation, e.g:
```html
<input ... ng-pattern="ps-regex" />
<!-- 
// pw-regex: /^.*(?=.{8,})(?=.*[a-zA-Z])(?=.*\d)(?=.*[!#$%&? "]).*$/
```

**Comment by tak215** [comment]
Sorry for late reply. I'm still configuring how to use GitHub..
@a8m I did now know about ng-pattern, I think that SHOULD solve the problem. 

@mallowigi I agree. Maybe it's a little stretch to generalize.

**Comment by tak215** [comment]
That would be more abstract and easily configurable. I say go for it.

**Comment by ctjhoa** [comment]
@a8m features merged. Close issue please.

**Comment by a8m** [comment]
@ctjhoa 
Thx
