### ISSUE TITLE
Filter "where" is unable to perform equality check on false value

### ISSUE THREAD

**Issue by ccortezia** [a8m/angular-filter#77]
I am unable to apply a "where" filter over an object trying to match a property whose value is false. The example below should illustrate my scenario. On the excerp below, ng-repeat will not be repeated:

```html
<div ng-repeat="item in [{prop:false}, {prop:true}] | where: {prop: false}">
    item: {{ item.prop }}
</div>
```

Now, with this new filter spec, the repetition will occur as expected:

```html
<div ng-repeat="item in [{prop:false}, {prop:true}] | where: {prop: true}">
    item: {{ item.prop }}
</div>
```

**Comment by ccortezia** [comment]
I see now that my understanding on this filter was wrong. This is not a property's value checking filter, but a property's existence checking one. Gonna close it alright.

**Comment by ccortezia** [comment]
Well, unfortunately I think my initial understanding was correct (in that "where" really check for properties values). My initial claim seem valid once again.

PS: sorry for the noise.

**Comment by mallowigi** [comment]
Which version are you using? This bug have been fixed in the latest version (0.5.2)

**Comment by ccortezia** [comment]
I am on 0.5.1. Just got it from bower registry. Is 0.5.2 already bower ready ?

**Comment by a8m** [comment]
@ccortezia , see: **v0.5.2**
Thanks.

**Comment by ccortezia** [comment]
Ok. Bower seems to be properly getting 0.5.2 now. Thanks !

**Comment by a8m** [comment]
Awesome @ccortezia 
Thanks.
