### ISSUE TITLE
Contains doesn't refresh on value change

### ISSUE THREAD

**Issue by hadokee** [a8m/angular-filter#81]
I'm using contains directive with input from inputbox:

`<input type="text" ng-model="search"/>`
`<div ng-show="{{ tags | contains: search }}">`

Directive ng-show doesn't refresh on search input changes.

**Comment by a8m** [comment]
See: [example](http://jsbin.com/gitefo/3/edit?html,js,output)
Thanks.

**Comment by hadokee** [comment]
it works perfect.
Thanks you!

**Comment by a8m** [comment]
Awesome.
Thanks
