### ISSUE TITLE
Use a filter in another one

### ISSUE THREAD

**Issue by DavidePastore** [a8m/angular-filter#83]
How can I call a filter in another one? I'm trying to do something like this but it doesn't work:

    angular.module('a8m.math.mean', ['a8m.math.sum'])

     .filter('mean', ['$math', '$parse', function ($math, $parse) {
        return function (input) {

          if(!isArray(input)) {
            return input;
          }
         return $math.sum(input) / input.length;
        };

      }]);

**Comment by a8m** [comment]
According to your example:
```js
angular.module('a8m.math.mean', ['a8m.math.sum'])
  // use [name]Filter to get specific filter
 .filter('mean', ['sumFilter', '$parse', function (sumFilter, $parse) {
    // ...
    };
  }])
  // or use the `$filter` service
  .filter('mean', ['$filter', '$parse', function ($filter, $parse) {
    var sum = $filter('sum')
    // ...
    };
  }]);
```

**Comment by DavidePastore** [comment]
@a8m Thanks so much, it works! :dancer:

**Comment by a8m** [comment]
Awesome @DavidePastore 
Thanks.
