### ISSUE TITLE
Count object of array inside of array

### ISSUE THREAD

**Issue by rpinto** [a8m/angular-filter#93]
I have a question regarding the usage of angular-filter.
Let's imagine I have an array of objects that have arrays inside, eg:
[{id: 1, props: [{id: 11, name: "A", property: true}, {id: 12, name: "Z", property: false}]}, 
{id: 2, props: [{id: 21, name: "B", property: true}, {id: 22, name: "Y", property: true}]}, 
{id: 3, props: [{id: 31, name: "C", property: false}, {id: 32, name: "X", property: true}]}]

The intention is to count the number of properties that are true: the number should be 4.
I'm having a bit of trouble reaching that number...

**Comment by mallowigi** [comment]
```html
<p>{{ coll | map:'props' | flatten | countBy:'property' }}</p>
```

**Comment by mallowigi** [comment]
This however would not taking property:true in the object level.

**Comment by mallowigi** [comment]
Btw I'm amazed that there isn't a filter to compute the size of an array without using countBy, something like 'length'

**Comment by rpinto** [comment]
Thanks mallowigi.

<p>{{ (coll | map:'props' | flatten | countBy:'property' | where: {property: true}).length }}</p>
