### ISSUE TITLE
mantain object keys

### ISSUE THREAD

**Issue by satore11** [a8m/angular-filter#98]
Hi,
why when I add a fuzy filter, my object keys are reset?
Look the example:
The original object is as follows:
```javascript
var items = {
    10: {...},
    20: {...},
    ...
};
```
when I try to filter the object so:
```html
<div ng-repeat="(key, val) in items | fuzy:searchField" > {{key}} </div>
```
the result I expect is
```html
<div>10</div>
<div>20</div>
<div>...</div>
<!-- but the result i get is -->
<div>0</div>
<div>1</div>
<div>...</div>
```
with the library, the keys are reset as an array ( with indexes ), without the filters of the lib, the keys return to the original.
sorry for my bad english :)

**Comment by a8m** [comment]
@satore11 you should use `toArray` of you care about the `key`.
see: [jsbin](http://jsbin.com/jireni/1/edit?html,js,output)

**Comment by satore11** [comment]
It works.
@a8m thank you verry much

**Comment by a8m** [comment]
Cheers :beers:

**Comment by diazgilberto** [comment]
In my use case, if I use `toArray: true`, `groupBy: 'bid'` stop working. If I take `groupBy: 'bid'` off, `toArray: true` works. Here is a screen shot with out `groupBy: 'bid'`...

<img width="1149" alt="screen shot 2017-03-06 at 2 28 47 pm" src="https://cloud.githubusercontent.com/assets/9165819/23628262/638e8b96-0279-11e7-822e-1ab09b4b90b6.png">

Here is a screen shot with `groupBy: 'bid'`...

<img width="1149" alt="screen shot 2017-03-06 at 2 28 15 pm" src="https://cloud.githubusercontent.com/assets/9165819/23628303/7c722c6c-0279-11e7-828f-08a31d240a61.png">

Here is my code...

```
<div class="grid" ng-repeat="item in schedule[0] | toArray: true | fuzzy: search">
    <h3 class="barber-name">{{item.bid}}</h3>
    {{item | json}}
    <div class="grid__column--12">
        <div class="card">
            <div class="card__content">
                <ul class="list list--unstyled">
                    <li class="list__item">{{item.name}}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
```

```
<div class="grid" ng-repeat="(key, items) in schedule[0] | groupBy: 'bid' | fuzzy: search">
    <div class="grid__column--12">
        <h3 class="barber-name">{{key}}</h3>
        {{key | json}}
        <div class="card">
            <div class="card__content">
                <ul class="list list--unstyled" ng-repeat="item in items">
                    <li class="list__item">{{item.name}}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
```

How can I make both work together?
